version: "3.8"
services:
  node-app:
    image: node:18
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - DB_PATH=/usr/src/app/data/database.sqlite
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - sqlite
    restart: on-failure

  redis:
    image: redis:7
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_HOST=${REDIS_HOST}
    restart: always

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DB=/data/database.sqlite
    restart: on-failure

    # postgres:
    #   image: postgres:14
    #   container_name: postgres-db
    #   ports:
    #     - "5432:5432"
    #   environment:
    #     - POSTGRES_USER=${POSTGRES_USER}
    #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #     - POSTGRES_DB=${POSTGRES_DB}
    #   volumes:
    #     - ./postgres-data:/var/lib/postgresql/data
    #   restart: on-failure
